/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://kguwfs2cpbbofka4rqwualgxdu.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tb6u3532ljhk5hexg3nkstez7u",
    "aws_cognito_identity_pool_id": "ap-south-1:1278d546-f33b-4821-a201-c78117f596b1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_RILVfUGru",
    "aws_user_pools_web_client_id": "5v634a980tui4idcci0o404gie",
    "oauth": {},
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PROFILE",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    }
};


export default awsmobile;
